apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stylerhun/multi-server
          ports:
            - containerPort: {{.Values.ports.api}}
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: {{.Values.ports.postgres}}
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
