apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: { { .Values.ports.api } }
      targetPort: { { .Values.ports.api } }
